### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by WireWolf** [DMeville/Unity-Fast-Dual-Contouring#7]
Where can I input my voxel data to generate the mesh and what kind of input does it require?

**Comment by DMeville** [comment]
It generates the mesh data from a SDF density function.

If using the C++ plugin the density function here - https://github.com/DMeville/Unity-Fast-Dual-Contouring/blob/master/C%2B%2BSource/Testbed/DCTest/DCTest/DCTest/DualContouringPlugin/DualContouringPlugin/density.cpp
If using the C# version the density function here- https://github.com/DMeville/Unity-Fast-Dual-Contouring/blob/master/Assets/DualContouring.cs

This code is not production ready, but rather a starting point if anyone wants to use it!

**Comment by WireWolf** [comment]
Thanks for the quick reply
